export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS';
export const ADD_POST = 'ADD_POST';

export const LOAD_HELPDESKS_SUCCESS = 'LOAD_HELPDESKS_SUCCESS';
export const LOAD_HELPDESKS_RESOLVED_SUCCESS = 'LOAD_HELPDESKS_RESOLVED_SUCCESS';
export const ADD_HELPDESK = 'ADD_HELPDESK';
