-- MySQL Script generated by MySQL Workbench
-- Sun May 28 13:56:33 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kondo_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kondo_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kondo_app` ;
USE `kondo_app` ;

-- -----------------------------------------------------
-- Table `kondo_app`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kondo_app`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` TEXT NULL,
  `content` TEXT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
